pipeline:
  - step: CreateVEnv
    module: pypeline.steps.create_venv
    config:
      package_manager: poetry==2.2.1
      python_executable: python3
  - step: PreCommit
    run: pre-commit run --all-files
  - step: PyTest
    run: pytest
  - step: Docs
    run: sphinx-build -E -a docs docs/_build